name: "Deploy to OVHcloud"

on:
  push:
    branches:
      - glitch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        env:
          OVH_HOSTING_DOMAIN: ${{ secrets.OVH_HOSTING_DOMAIN }}
          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
        run: |
          echo "Deploying"
          sshpass -p "$OVH_HOSTING_PASSWORD" rsync -av  --exclude '.*' --exclude 'LICENSE' -e "ssh -o StrictHostKeyChecking=no" . $OVH_HOSTING_USER@$OVH_HOSTING_DOMAIN:~/resume.mlcdf.fr